node {
    def revision = env.BUILD_NUMBER

    stage('Build') {
        docker.image('maven:3.6.1-jdk-8-alpine').inside {
            git url: 'https://github.com/Archi-Lab/prox-service-discovery.git'
            git branch: 'jenkins-migration'

            writeFile file: 'settings.xml', text: "<settings><localRepository>${pwd()}/.m2</localRepository></settings>"

            withCredentials([usernamePassword(credentialsId: 'archilab-nexus-jenkins', usernameVariable: 'NEXUS_USERNAME', passwordVariable: 'NEXUS_PASSWORD')]) {
               sh "mvn -B -s settings.xml -Ddockerfile.username=\"$NEXUS_USERNAME\" -Ddockerfile.password=\"$NEXUS_PASSWORD\" -Drevision=${revision} clean deploy"
            }
        }
    }

    stage('Deploy') {
        docker.withServer('tcp://10.10.10.41:2376', 'prox-prod-certs') {
            def pom = readMavenPom file: 'pom.xml'
            def image = pom.getArtifactId()
            def release = pom.getProperties().getProperty('release')
            def tag = "${release}" + '-' + "${revision}"

            docker.withRegistry('https://docker.nexus.archi-lab.io', 'archilab-nexus-jenkins') {
                sh "env IMAGE=${image} TAG=${tag} docker stack deploy --with-registry-auth -c src/main/docker/docker-compose.yml -c src/main/docker/docker-compose.prod.yml ${image}"
            }
        }
    }
}
