node {
    def revision = env.BUILD_NUMBER

    stage('Build') {
        withCredentials([usernamePassword(credentialsId: 'archilab-nexus-jenkins', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
            docker.image('maven:3.6.1-jdk-8-alpine').inside {
                git url: 'https://github.com/Archi-Lab/prox-service-discovery.git'
                git branch: 'jenkins-migration'

                writeFile file: 'settings.xml', text: "<settings><localRepository>${pwd()}/.m2</localRepository></settings>"

                sh "mvn -B -s settings.xml -Ddockerfile.username=${DOCKER_USER} -Ddockerfile.password=${DOCKER_PASSWORD} -Drevision=${revision} clean deploy"
            }
        }
    }

    stage('Deploy') {
        docker.withServer('tcp://10.10.10.41:2376', 'prox-prod-certs') {
            def pom = readMavenPom file: 'pom.xml'
            def image = pom.getArtifactId()
            def release = pom.getProperties().getProperty('release')
            def tag = "${release}" + '-' + "${revision}"

            docker.withRegistry('https://docker.nexus.archi-lab.io', 'archilab-nexus-jenkins') {
                sh "env IMAGE=${image} TAG=${tag} docker stack deploy -c src/main/docker/docker-compose.yml ${image}"
            }
        }
    }
}
